### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by zack-zzq**

### CODE REVIEW

**Review by nvb-uy — CHANGES_REQUESTED** [review]
- The name of the mod must not be translated
- Characters should not be translated

**Comment by zack-zzq** [comment]
I see...
I'll make some changes later

**Comment by nvb-uy** [comment]
Alright, thank you :D

**Comment by zack-zzq** [comment]
@nvb-uy 
- For the mod name I kept the original (Eldritch End);
- For the character names, I kept the original text, except for a few where there are agreed Chinese translations (Hastur, [哈斯塔](https://zh.wikipedia.org/zh-cn/%E5%93%88%E6%96%AF%E5%A1%94)).

**Review by nvb-uy — APPROVED** [review]

**Pull request merged**
